"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
type Status="Belum dibuat"|"Sedang dibuat"|"Siap";
type Order={id:number;orderNo:string;customer:string;phone:string;product:string;details:string;quantity:number;total:number;paymentStatus:string;status:Status;dueDate:string;notes:string;createdAt:string};
const products=["Clicker","Nametag","Fridge Magnet","NFC Tag","Photo","Kopi","Kad PSS","Lain-lain"];
const empty={customer:"",phone:"",product:"Clicker",details:"",quantity:"1",total:"",paymentStatus:"Sudah bayar",status:"Belum dibuat",dueDate:"",notes:""};
export default function Home(){
 const[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[filter,setFilter]=useState<"Semua"|Status>("Semua"),[query,setQuery]=useState(""),[showAdd,setShowAdd]=useState(false),[form,setForm]=useState(empty),[saving,setSaving]=useState(false);
 async function load(){setLoading(true);try{const r=await fetch("/api/orders");const d=await r.json();if(!r.ok)throw 0;setOrders(d.orders||[]);setError("")}catch{setError("Order belum dapat dimuatkan. Cuba muat semula.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const shown=useMemo(()=>orders.filter(o=>(filter==="Semua"||o.status===filter)&&(`${o.orderNo} ${o.customer} ${o.product} ${o.phone}`.toLowerCase().includes(query.toLowerCase()))),[orders,filter,query]);
 const counts={new:orders.filter(o=>o.status==="Belum dibuat").length,making:orders.filter(o=>o.status==="Sedang dibuat").length,done:orders.filter(o=>o.status==="Siap").length};
 const sales=orders.reduce((s,o)=>s+Number(o.total),0);
 async function addOrder(e:FormEvent){e.preventDefault();setSaving(true);try{const r=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw 0;setOrders(v=>[d.order,...v]);setForm(empty);setShowAdd(false)}catch{setError("Order tidak berjaya disimpan.")}finally{setSaving(false)}}
 async function updateStatus(order:Order,status:Status){const prev=orders;setOrders(v=>v.map(o=>o.id===order.id?{...o,status}:o));const r=await fetch("/api/orders",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:order.id,status})});if(!r.ok){setOrders(prev);setError("Status tidak berjaya dikemas kini.")}}
 async function remove(order:Order){if(!confirm(`Padam ${order.orderNo} — ${order.customer}?`))return;const r=await fetch(`/api/orders?id=${order.id}`,{method:"DELETE"});if(r.ok)setOrders(v=>v.filter(o=>o.id!==order.id));else setError("Order tidak berjaya dipadam.")}
 return <main className="tracker"><aside><div className="brand"><span>K</span><div><b>Kedai Cikgujiwa</b><small>Order Tracker</small></div></div><nav><button className={filter==="Semua"?"active":""} onClick={()=>setFilter("Semua")}><span>▦</span> Semua order</button><button className={filter==="Belum dibuat"?"active":""} onClick={()=>setFilter("Belum dibuat")}><span>◷</span> Belum dibuat <i>{counts.new}</i></button><button className={filter==="Sedang dibuat"?"active":""} onClick={()=>setFilter("Sedang dibuat")}><span>◌</span> Sedang dibuat <i>{counts.making}</i></button><button className={filter==="Siap"?"active":""} onClick={()=>setFilter("Siap")}><span>✓</span> Siap <i>{counts.done}</i></button></nav><div className="aside-note"><b>Aliran kerja</b><p>Masukkan order WhatsApp, kemudian tukar status apabila anda mula dan siap membuatnya.</p></div><div className="owner"><span>CJ</span><div><b>Cikgujiwa</b><small>Dashboard peribadi</small></div></div></aside>
 <section className="workspace"><header><div><p>Dashboard peribadi</p><h1>Order Tracker</h1></div><button className="add" onClick={()=>setShowAdd(true)}>＋ Tambah order</button></header><div className="summary"><article><span>Belum dibuat</span><strong>{counts.new}</strong><small>Order menunggu</small><i className="orange">◷</i></article><article><span>Sedang dibuat</span><strong>{counts.making}</strong><small>Dalam proses</small><i className="blue">◌</i></article><article><span>Sudah siap</span><strong>{counts.done}</strong><small>Boleh dihantar/diambil</small><i className="yellow">✓</i></article><article><span>Jumlah jualan</span><strong>RM{sales.toFixed(2)}</strong><small>Semua order</small><i className="green">RM</i></article></div>
 <div className="panel"><div className="panel-head"><div><h2>Senarai order</h2><p>{shown.length} daripada {orders.length} order</p></div><div className="actions"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari nama atau produk"/></label><div className="filters">{(["Semua","Belum dibuat","Sedang dibuat","Siap"] as const).map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div></div></div>{error&&<div className="error">{error}<button onClick={load}>Cuba lagi</button></div>}{loading?<div className="empty">Memuatkan order…</div>:shown.length===0?<div className="empty"><span>✓</span><h3>Tiada order di sini</h3><p>Tekan “Tambah order” apabila tempahan WhatsApp masuk.</p></div>:<div className="order-list">{shown.map(o=><article className={o.status==="Siap"?"completed":""} key={o.id}><div className="order-main"><div className="avatar">{o.customer.slice(0,2).toUpperCase()}</div><div><div className="order-title"><b>{o.customer}</b><span>{o.orderNo}</span></div><p>{o.product} · {o.quantity} unit {o.details&&`· ${o.details}`}</p><small>{o.phone||"Tiada nombor telefon"}{o.dueDate&&` · Perlu siap: ${new Date(o.dueDate+"T00:00:00").toLocaleDateString("ms-MY")}`}</small></div></div><div className="payment"><small>{o.paymentStatus}</small><b>RM{Number(o.total).toFixed(2)}</b></div><select className={`status ${o.status.replaceAll(" ","-").toLowerCase()}`} value={o.status} onChange={e=>updateStatus(o,e.target.value as Status)}><option>Belum dibuat</option><option>Sedang dibuat</option><option>Siap</option></select><button className="delete" onClick={()=>remove(o)} title="Padam order">•••</button></article>)}</div>}</div></section>
 {showAdd&&<div className="modal-bg"><form className="modal" onSubmit={addOrder}><div className="modal-head"><div><p>Order WhatsApp</p><h2>Tambah order baru</h2></div><button type="button" onClick={()=>setShowAdd(false)}>×</button></div><div className="form-grid"><label>Nama pelanggan<input required value={form.customer} onChange={e=>setForm({...form,customer:e.target.value})} placeholder="Contoh: Aina"/></label><label>No. WhatsApp<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="01X-XXXXXXX"/></label><label>Produk<select value={form.product} onChange={e=>setForm({...form,product:e.target.value})}>{products.map(p=><option key={p}>{p}</option>)}</select></label><label>Kuantiti<input required min="1" type="number" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label className="wide">Butiran tempahan<input value={form.details} onChange={e=>setForm({...form,details:e.target.value})} placeholder="Nama, warna, saiz atau maklumat penting"/></label><label>Jumlah (RM)<input required min="0" step="0.01" type="number" value={form.total} onChange={e=>setForm({...form,total:e.target.value})} placeholder="0.00"/></label><label>Bayaran<select value={form.paymentStatus} onChange={e=>setForm({...form,paymentStatus:e.target.value})}><option>Sudah bayar</option><option>Belum bayar</option><option>Deposit</option></select></label><label>Tarikh perlu siap<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label>Status awal<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Belum dibuat</option><option>Sedang dibuat</option><option>Siap</option></select></label><label className="wide">Nota<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Nota tambahan (jika ada)"/></label></div><div className="modal-actions"><button type="button" onClick={()=>setShowAdd(false)}>Batal</button><button className="add" disabled={saving}>{saving?"Menyimpan…":"Simpan order"}</button></div></form></div>}</main>
}
