"use client";
import { useEffect,useMemo,useState } from "react";
type Status="Belum dibuat"|"Sedang dibuat"|"Siap";
type Order={key:string;sheet:string;row:number;customer:string;name:string;details:string;quantity:number;amount:number;payment:string;date:string;phone:string;status:Status};
const tabs=["Semua","CLICKER","PHOTO","MAGNET","NAMETAG","KOPI","NFC","KAD PSS"];
const tabLabel:Record<string,string>={CLICKER:"Clicker",PHOTO:"Photo",MAGNET:"Fridge Magnet",NAMETAG:"Nametag",KOPI:"Kopi",NFC:"NFC Tag","KAD PSS":"Kad PSS"};
const tabIcon:Record<string,string>={CLICKER:"C",PHOTO:"P",MAGNET:"M",NAMETAG:"N",KOPI:"K",NFC:"N","KAD PSS":"K"};
export default function Home(){
 const[orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[sync,setSync]=useState("");
 const[tab,setTab]=useState("Semua"),[status,setStatus]=useState<"Semua"|Status>("Semua"),[query,setQuery]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/orders",{cache:"no-store"});const d=await r.json();if(!r.ok)throw 0;setOrders(d.orders||[]);setSync(d.syncedAt);setError("")}catch{setError("Google Sheet tidak dapat dibaca sekarang. Cuba semula.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function change(o:Order,next:Status){const old=orders;setOrders(v=>v.map(x=>x.key===o.key?{...x,status:next}:x));const r=await fetch("/api/orders",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({key:o.key,status:next})});if(!r.ok){setOrders(old);setError("Status tidak berjaya disimpan.")}}
 const filtered=useMemo(()=>orders.filter(o=>(tab==="Semua"||o.sheet===tab)&&(status==="Semua"||o.status===status)&&`${o.customer} ${o.name} ${o.details}`.toLowerCase().includes(query.toLowerCase())),[orders,tab,status,query]);
 const counts={all:orders.length,new:orders.filter(o=>o.status==="Belum dibuat").length,making:orders.filter(o=>o.status==="Sedang dibuat").length,done:orders.filter(o=>o.status==="Siap").length};
 const sales=orders.reduce((s,o)=>s+o.amount,0),paid=orders.filter(o=>/paid|bayar/i.test(o.payment)).reduce((s,o)=>s+o.amount,0);
 const products=tabs.slice(1).map(t=>({tab:t,count:orders.filter(o=>o.sheet===t).length,total:orders.filter(o=>o.sheet===t).reduce((s,o)=>s+o.amount,0)})).sort((a,b)=>b.count-a.count);
 const max=Math.max(...products.map(p=>p.count),1);
 return <main className="sheet-dashboard"><aside><div className="brand"><span>K</span><div><b>Kedai Cikgujiwa</b><small>Operations</small></div></div><div className="nav-title">Menu utama</div><nav><button className="active"><span>▦</span> Dashboard</button><a href="https://docs.google.com/spreadsheets/d/12pkJMTSPvT6VEgHK9Xkjxrmf7g8kxx96geToszeXbbU/edit" target="_blank"><span>▤</span> Buka Google Sheet <i>↗</i></a></nav><div className="nav-title">Produk</div><div className="product-nav"><button className={tab==="Semua"?"active":""} onClick={()=>setTab("Semua")}><span>✦</span> Semua produk <i>{orders.length}</i></button>{tabs.slice(1).map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}><span>{tabIcon[t]}</span>{tabLabel[t]}<i>{orders.filter(o=>o.sheet===t).length}</i></button>)}</div><div className="sheet-live"><span></span><div><b>Google Sheet Live</b><small>{sync?`Diselaraskan ${new Date(sync).toLocaleTimeString("ms-MY",{hour:"2-digit",minute:"2-digit"})}`:"Menyambung…"}</small></div></div></aside>
 <section className="main-area"><header><div><p>Ringkasan operasi</p><h1>Selamat datang, Cikgujiwa</h1></div><button className="refresh" onClick={load} disabled={loading}><span className={loading?"spin":""}>↻</span>{loading?"Menyelaras…":"Segarkan data"}</button></header>
 <section className="metrics"><article><div><small>Jumlah order</small><strong>{counts.all}</strong><p>Daripada 7 kategori</p></div><i className="ico dark">▦</i></article><article><div><small>Belum dibuat</small><strong>{counts.new}</strong><p>Perlu tindakan</p></div><i className="ico orange">◷</i></article><article><div><small>Sedang dibuat</small><strong>{counts.making}</strong><p>Dalam produksi</p></div><i className="ico blue">◌</i></article><article><div><small>Sudah siap</small><strong>{counts.done}</strong><p>{counts.all?Math.round(counts.done/counts.all*100):0}% keseluruhan</p></div><i className="ico yellow">✓</i></article></section>
 <section className="insights"><article className="sales-card"><div className="card-title"><div><span>Nilai tempahan</span><h2>RM{sales.toLocaleString("en-MY",{minimumFractionDigits:2})}</h2></div><i>RM</i></div><div className="sales-split"><div><span>Direkod bayar</span><b>RM{paid.toLocaleString("en-MY",{minimumFractionDigits:2})}</b></div><div><span>Baki / belum ditanda</span><b>RM{Math.max(0,sales-paid).toLocaleString("en-MY",{minimumFractionDigits:2})}</b></div></div></article><article className="product-card"><div className="card-title"><div><span>Order mengikut produk</span><h3>Prestasi kategori</h3></div></div><div className="bars">{products.slice(0,5).map(p=><div key={p.tab}><span>{tabLabel[p.tab]}</span><div><i style={{width:`${p.count/max*100}%`}}></i></div><b>{p.count}</b></div>)}</div></article></section>
 <section className="orders-panel"><div className="orders-head"><div><h2>Senarai tempahan</h2><p>{filtered.length} order dipaparkan</p></div><div className="tools"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari pelanggan atau tempahan"/></label><select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option>Semua</option><option>Belum dibuat</option><option>Sedang dibuat</option><option>Siap</option></select></div></div>{error&&<div className="error">{error}<button onClick={load}>Cuba lagi</button></div>}
 {loading?<div className="empty">Menyelaraskan data Google Sheet…</div>:filtered.length===0?<div className="empty"><b>Tiada order ditemui</b><span>Cuba tukar carian atau penapis.</span></div>:<div className="table"><div className="tr table-header"><span>Pelanggan & tempahan</span><span>Produk</span><span>Bayaran</span><span>Jumlah</span><span>Status kerja</span></div>{filtered.map(o=><div className={`tr ${o.status==="Siap"?"is-done":""}`} key={o.key}><div className="customer"><i>{o.customer.slice(0,2).toUpperCase()}</i><div><b>{o.customer}</b><p>{o.name}{o.details&&` · ${o.details}`}</p><small>Baris {o.row} dalam Google Sheet</small></div></div><span className="pill product">{tabLabel[o.sheet]}</span><span className={`pay ${/paid|bayar/i.test(o.payment)?"paid":""}`}>{o.payment||"Belum ditanda"}</span><b className="amount">RM{o.amount.toFixed(2)}</b><select className={`status ${o.status.replaceAll(" ","-").toLowerCase()}`} value={o.status} onChange={e=>change(o,e.target.value as Status)}><option>Belum dibuat</option><option>Sedang dibuat</option><option>Siap</option></select></div>)}</div>}</section><footer>Data order dibaca terus daripada Google Sheet “ORDER BY KEDAICIKGUJIWA”. Status kerja disimpan dalam dashboard ini.</footer></section></main>
}
