import { env } from "cloudflare:workers";

const sheetId="12pkJMTSPvT6VEgHK9Xkjxrmf7g8kxx96geToszeXbbU";
const tabs=["CLICKER","PHOTO","MAGNET","NAMETAG","KOPI","NFC","KAD PSS"];
const initialDone:Record<string,number[]>={CLICKER:[2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137],NAMETAG:[2,3]};
async function ready(){await env.DB.prepare("CREATE TABLE IF NOT EXISTS sheet_status (order_key TEXT PRIMARY KEY, status TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run()}
function csv(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++}else quote=!quote}else if(c===","&&!quote){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!quote){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell=""}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function money(value=""){return Number(value.replace(/[^0-9.-]/g,""))||0}
type Item={key:string;sheet:string;row:number;customer:string;name:string;details:string;quantity:number;amount:number;payment:string;date:string;phone:string;status:string};
function normalize(tab:string,rows:string[][]){let lastCustomer="";return rows.slice(1).map((r,i):Item|null=>{const row=i+2;let customer="",name="",details="",quantity=1,amount=0,payment="",date="",phone="";
 if(tab==="CLICKER"){lastCustomer=r[0]||lastCustomer;customer=lastCustomer||"Pelanggan";name=r[1];details=[r[2],r[3],r[4]].filter(Boolean).join(" · ");amount=money(r[6]);payment=r[5]}
 else if(tab==="PHOTO"){customer=r[1];name=r[3]||"Photo";amount=money(r[2]);payment=r[4]}
 else if(tab==="MAGNET"){customer=r[0];name="Fridge Magnet";quantity=Number(r[1])||1;amount=money(r[2]);payment=r[3]}
 else if(tab==="NAMETAG"){customer=r[0];name=r[1]||"Nametag";amount=money(r[3]);payment=r[2]}
 else if(tab==="KOPI"){date=r[0];customer=r[1]||"Pelanggan";name="Kopi";quantity=Number(r[2])||1;amount=money(r[4]);payment=r[3]}
 else if(tab==="NFC"){date=r[0];customer=r[1];name=r[2]||"NFC Tag";details=[r[5],r[6],r[7]].filter(Boolean).join(" · ");amount=money(r[4]);payment=r[3];phone=r[9]||""}
 else {customer=r[1];name=`Kad PSS ${r[1]||""}`.trim();quantity=Number(r[2])||1;amount=money(r[3]);date=r[4];payment=r[5]}
 if(!customer&&!name&&!amount)return null;return{key:`${tab}-${row}`,sheet:tab,row,customer:customer||name||"Pelanggan",name:name||tab,details,quantity,amount,payment,date,phone,status:initialDone[tab]?.includes(row)?"Siap":"Belum dibuat"}}).filter(Boolean) as Item[]}
export async function GET(){try{await ready();const sets=await Promise.all(tabs.map(async tab=>{const url=`https://docs.google.com/spreadsheets/d/${sheetId}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(tab)}&t=${Date.now()}`;const res=await fetch(url,{cf:{cacheTtl:0} as never});if(!res.ok)throw new Error(`Gagal membaca ${tab}`);return normalize(tab,csv(await res.text()))}));const{results}=await env.DB.prepare("SELECT order_key,status FROM sheet_status").all<{order_key:string,status:string}>();const status=new Map(results.map(r=>[r.order_key,r.status]));const orders=sets.flat().map(o=>({...o,status:status.get(o.key)||o.status}));return Response.json({orders,syncedAt:new Date().toISOString(),sheetUrl:`https://docs.google.com/spreadsheets/d/${sheetId}/edit`},{headers:{"cache-control":"no-store"}})}catch(e){return Response.json({error:e instanceof Error?e.message:"Gagal membaca Google Sheet"},{status:500})}}
export async function PATCH(req:Request){try{await ready();const p=await req.json() as{key?:string;status?:string};if(!p.key||!["Belum dibuat","Sedang dibuat","Siap"].includes(p.status||""))return Response.json({error:"Status tidak sah"},{status:400});await env.DB.prepare("INSERT INTO sheet_status(order_key,status,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(order_key) DO UPDATE SET status=excluded.status,updated_at=CURRENT_TIMESTAMP").bind(p.key,p.status).run();return Response.json({ok:true})}catch(e){return Response.json({error:e instanceof Error?e.message:"Gagal mengemas kini"},{status:500})}}
